return {
    ["workshop-347079953"]={
      configuration_options={ DFV_Language="CN", DFV_MinimalMode="default" },
      enabled=true 
    },
    ["workshop-378160973"]={
      configuration_options={
        ENABLEPINGS=true,
        FIREOPTIONS=1,
        OVERRIDEMODE=false,
        SHAREMINIMAPPROGRESS=true,
        SHOWFIREICONS=true,
        SHOWPLAYERICONS=true,
        SHOWPLAYERSOPTIONS=3 
      },
      enabled=true 
    },
    ["workshop-666155465"]={
      configuration_options={
        chestB=-1,
        chestG=-1,
        chestR=-1,
        display_hp=-1,
        food_estimation=-1,
        food_order=0,
        food_style=0,
        lang="chs",
        show_food_units=-1,
        show_uses=-1 
      },
      enabled=true 
    },
    ["workshop-375859599"]={
      enabled=true
    },
    ["workshop-362175979"]={
      enabled=true
    },
    ["workshop-375850593"]={
      enabled=true
    },
    ["workshop-1595631294"]={
      enabled=true
    },
    ["workshop-365119238"]={
      enabled=true
    },
    ["workshop-1301033176"]={
      enabled=true
    },
    ["workshop-1185229307"]={
      configuration_options={
        [""]="",
        DAMAGE_NUMBERS=true,
        DAMAGE_RESISTANCE=true,
        FRAME_PHASES=true,
        HORIZONTAL_OFFSET=0,
        NOEPIC=false,
        NONOEPIC=false,
        WETNESS_METER=false 
      },
      enabled=true 
    },
    ["workshop-2753774601"]={
      configuration_options={ [""]=0, CD=0, Health_Penalty=0.15, Language=false, UI="right_above" },
      enabled=true 
    },
    ["workshop-462434129"]={
      configuration_options={
        MOD_RESTART_ALLOW_KILL=true,
        MOD_RESTART_ALLOW_RESTART=true,
        MOD_RESTART_ALLOW_RESURRECT=false,
        MOD_RESTART_CD_BONUS=0,
        MOD_RESTART_CD_KILL=3,
        MOD_RESTART_CD_MAX=0,
        MOD_RESTART_CD_RESTART=3,
        MOD_RESTART_CD_RESURRECT=1,
        MOD_RESTART_FORCE_DROP_MODE=0,
        MOD_RESTART_IGNORING_ADMIN=true,
        MOD_RESTART_MAP_SAVE=2,
        MOD_RESTART_RESURRECT_HEALTH=0,
        MOD_RESTART_TRIGGER_MODE=1,
        MOD_RESTART_WELCOME_TIPS=false,
        MOD_RESTART_WELCOME_TIPS_TIME=6 
      },
      enabled=true 
    },
    ["workshop-501385076"]={
      configuration_options={
        quick_cook_on_fire=true,
        quick_harvest=true,
        quick_pick_cactus=true,
        quick_pick_plant_normal_ground=true 
      },
      enabled=true 
    },
    ["workshop-2119742489"]={
      configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
      enabled=true 
    }
  }